In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [2]:
import sys
sys.path.append('/content/gdrive/MyDrive/ACSE-9')

In [3]:
from numpy import *
from math  import *
import sys, os
import numpy as np
!pip install vtk -q
import vtk
import vtktools
import matplotlib.pyplot as plt
import datetime, time
import pprint as pprint
import joblib

     |████████████████████████████████| 59.5 MB 49 kB/s 
     |████████████████████████████████| 3.1 MB 56.2 MB/s 
     |████████████████████████████████| 495 kB 60.1 MB/s 
     |████████████████████████████████| 3.2 MB 43.0 MB/s 
     |████████████████████████████████| 74 kB 2.5 MB/s 
     |████████████████████████████████| 251 kB 66.2 MB/s 
     |████████████████████████████████| 1.3 MB 43.7 MB/s 
     |████████████████████████████████| 294 kB 60.5 MB/s 
     |████████████████████████████████| 142 kB 63.5 MB/s 


Helper functions

In [ ]:
#-- Function to read data in a text file         -#
#-------------------------------------------------#
def ReadData(path,filename,extension):

    output = []

    sf = open(path+filename+extension, 'r')
    data = sf.readlines()

    for i in range(0,len(data)):
        x = str.split(data[i])
        y = [float(v) for v in x]
        output.append(y)
    return output

#-------------------------------------------------#
#-- Function to initialise vtk files             -#
#-------------------------------------------------#
def Initialisation(filename):

    # Read file
    print ('     Read file')
    if filename[-4:] == ".vtu":
        gridreader=vtk.vtkXMLUnstructuredGridReader()
    elif filename[-5:] == ".pvtu":
        gridreader=vtk.vtkXMLPUnstructuredGridReader()
    gridreader.SetFileName(filename)
    gridreader.Update()
    ugrid=gridreader.GetOutput()

    return ugrid

#-------------------------------------------------#
#-- Function to initialise probe filter          -#
#-------------------------------------------------#
def InitialisePointData(ugrid, coordinates):

    # Initialise probe
    points = vtk.vtkPoints()
    points.SetDataTypeToDouble()

    # Create points to be extracted
    print ('     Gathering  coordinates')
    NrbPoints = 0
    for nodeID in range(len(coordinates)):
        NrbPoints += 1
        points.InsertNextPoint(coordinates[nodeID][0], coordinates[nodeID][1], coordinates[nodeID][2])

    print ('           Set points into data...')
    polydata = vtk.vtkPolyData()
    polydata.SetPoints(points)
    probe = vtk.vtkProbeFilter()

    print ('           Map data into probe...', 'VTK version ::', vtk.vtkVersion.GetVTKMajorVersion(),'.', vtk.vtkVersion.GetVTKMinorVersion())
    if vtk.vtkVersion.GetVTKMajorVersion() <= 5:
        probe.SetInput(polydata)
        probe.SetSource(ugrid)
    else:
        probe.SetInputData(polydata)
        probe.SetSourceData(ugrid)

    probe.Update()
    
    return probe, points, NrbPoints

#-------------------------------------------------#
#-- Function to initialise cell filter           -#
#-------------------------------------------------#
def InitialiseCellLocator(ugrid):

    # Initialise locator
    print ('     Initialise cell Locator')
    CellLocator = vtk.vtkCellLocator()
    CellLocator.SetDataSet(ugrid)
    CellLocator.Update()
    
    return CellLocator

#-------------------------------------------------#
#-- Function to do the rotation                  -#
#-------------------------------------------------#
def Rotation(coord_old, theta, x_centre, y_centre):
    
    rotation = np.array([[np.cos(np.radians(theta)), -np.sin(np.radians(theta))],
                        [ np.sin(np.radians(theta)), np.cos(np.radians(theta))]])
    tmp = np.array(coord_old)[:,[0,1]] - [x_centre, y_centre]
    tmp = np.dot(tmp,rotation)
    tmp = tmp + [x_centre, y_centre]
    coord_new = np.append(tmp,np.array(coord_old)[:,[2]], axis=1)

    return coord_new

In [ ]:
#--------------------------------#
#-- Choose variables           --#
#--------------------------------#
# Vtu files
#path      = '../Simu/run_Clip_ToSend/'
path      = '/content/gdrive/MyDrive/ACSE-9/ClarenceCentre/run_Clip_ToSend/'
extension = '.vtu'
name_simu = 'ClarenceCentre'
fieldname = 'CO2_ppm'
vtu_start = 0
#vtu_end = 3
vtu_end = 410
# vtu_end   = 455
vtu_step  = 1


#--------------------------------#
#-- Geometry input variables   --#
#--------------------------------#

# Geometry variables
Pi = np.pi

theta = 110.0  # Angle of rotation

#-- Size of the building in which the room is
lz_box1 = 9.0  # Length in the z-direction
lx_box1 = 48.0 # Length in the x-direction
ly_box1 = 8.11 # Length in the y-direction

#-- Position of the building in which the room is
dx_box = 20.0 * lz_box1 # x Position
dy_box = 6.0  * lz_box1 # y Position
dz_box = 0.0            # z Position

e_room  = 0.5 # Thickness of the walls 50cm

#-- Centre of the building (needed for rotation)
x_centre = dx_box + lx_box1
y_centre = dy_box + ly_box1
print ('x_centre', x_centre, 'y_centre', y_centre)

#-- Parameters to define the room
x_room = 42.2    # x position of the left hand side corner
y_room = e_room  # y position of the left hand side corner
z_room = 6.08    # z position of the left hand side corner

#-- Dimensions of the room
lx_room = 5.3  # Length of the room
ly_room = 7.11 # Width of the room
lz_room = 2.42 # Height of the room

#-- Min and max coordiantes of the room - before rotation
xmin = dx_box+x_room
xmax = dx_box+x_room+lx_room
ymin = dy_box+y_room 
ymax = dy_box+y_room+ly_room 
zmin = dz_box+z_room
zmax = dz_box+z_room+lz_room

print ('Before Coordinate Rotation')
print ('xmin::', xmin, ' xmax::', xmax)
print ('ymin::', ymin, ' ymax::', ymax)
print ('zmin::', zmin, ' zmax::', zmax)

# --------------------------#
# -- Coordinates Fluidity --#
#---------------------------#
coordinates = []

tap1 = [xmax-1.0,  ymin+0.1,  zmin+0.9]
tap2 = [xmax-4.3,  ymin+0.1,  zmin+0.9]
tap3 = [xmax-1.7,  ymin+7.0,  zmin+0.9]
tap4 = [xmax-0.1 , ymin+4.14, zmin+1.2]
tap5 = [xmax-5.2 , ymin+3.14, zmin+1.22]
tap6 = [xmax-4.53, ymin+6.17, zmin+2.4]
tap7 = [xmax-2.65, ymin+4.14, zmin+0.79]

coord_init = np.array([tap1,  tap2,  tap3,  tap4,  tap5,  tap6,  tap7])

print ('\n Coordinates Concentration Init::')
print (coord_init)

coordinates = Rotation(coord_init, theta, x_centre, y_centre)

print ('\n Coordinates Concentration ::')
print (coordinates)

#-- Write Coordinates

# sys.exit('\n EXIT HERE')

#---------------------------------------------------------------------
# EXTRACT DATA
#---------------------------------------------------------------------
tic = time.time()

#-- CO2
CO2     = []

#-- Time
TimeVTU = []

r = 0

for vtuID in range(vtu_start,vtu_end,vtu_step):
    filename=path+name_simu+'_'+str(vtuID)+extension
    print ('\n\n  '+str(filename))

    CO2.append([])
    
    # Read file
    ugrid = Initialisation(filename)

    # Initialise probe
    probe, points, NrbPoints = InitialisePointData(ugrid, coordinates)

    # Initialise cell location
    CellLocator = InitialiseCellLocator(ugrid)

    #-- Check Validity of points
    print ('           Check point Validity')
    valid_ids = probe.GetOutput().GetPointData().GetArray('vtkValidPointMask')
    validPoints = vtktools.arr([valid_ids.GetTuple1(i) for i in range(NrbPoints)])
    print ('           ... ', len(validPoints)-np.sum(validPoints), 'invalid points')

    # Extract data
    print ('     Extract Data')
    for nodeID in range(len(coordinates)):
        # If valid point, extract using probe,
        # Otherwise extract the cell:
        #    If no cell associated - then it is really a non-valid point outside the domain
        #    Otherwise: do the average over the cell values - this provide the tracer value.
        # We need to do that as it is a well-known bug in vtk libraries - sometimes it returns an invalid node while it is not...
        if validPoints[nodeID] == 1:
            tmp = probe.GetOutput().GetPointData().GetArray(fieldname).GetValue(nodeID)
            CO2[r].append(tmp)
        else:
            coord_tmp = np.array(points.GetPoint(nodeID))
            cellID =  CellLocator.FindCell(coord_tmp) # cell ID which contains the node
            idlist=vtk.vtkIdList()
            ugrid.GetCellPoints(cellID, idlist)
            pointsID_to_cellID = np.array([idlist.GetId(k) for k in range(idlist.GetNumberOfIds())]) # give all the points asociated with this cell
            if len(pointsID_to_cellID) == 0: # Non-valid points - We assign negative value - like that we know we are outside the domain
                CO2[r].append(-1e20)
            else:
                tmp = 0
                for pointID in pointsID_to_cellID:
                    tmp += ugrid.GetPointData().GetArray(fieldname).GetTuple(pointID)[0]
                tmp = tmp/len(pointsID_to_cellID)
                CO2[r].append(tmp)
        # print("nodeID: ", valid_ids)

    # Time
    time_tmp = probe.GetOutput().GetPointData().GetArray('Time').GetValue(0)
    TimeVTU.append(time_tmp)
    print ('      Time ::', time_tmp)
    print ('      CO2  ::', CO2[r])

    r += 1

print ('\n Time in (s) ::')
print (TimeVTU)    
np.savetxt('TimeVTU.dat',TimeVTU)

print ('\n CO2 ::')
CO2 = np.array(CO2)
print (CO2)
CO2_all = [np.array(TimeVTU)]
CO2_all = np.transpose(np.append(CO2_all, np.transpose(CO2), axis = 0))

# joblib.dump(CO2, '/content/gdrive/MyDrive/ACSE-9/models/sensor_CO2_410.pkl') #CO2 data -> ( nSnapshot x 7(sensors) )
# joblib.dump(CO2_all, '/content/gdrive/MyDrive/ACSE-9/models/CO2_Fluidity_410.pkl') #with the time column
# joblib.dump(CO2, '/content/gdrive/MyDrive/ACSE-9/models/sensor_CO2_all.pkl') #CO2 data -> ALL time levels

toc = time.time()

print ('\n\nTime : ', toc - tic, 'sec')

x_centre 228.0 y_centre 62.11
Before Coordinate Rotation
xmin:: 222.2  xmax:: 227.5
ymin:: 54.5  ymax:: 61.61
zmin:: 6.08  zmax:: 8.5

 Coordinates Concentration Init::
[[226.5   54.6    6.98]
 [223.2   54.6    6.98]
 [225.8   61.5    6.98]
 [227.4   58.64   7.28]
 [222.3   57.64   7.3 ]
 [222.97  60.67   8.48]
 [224.85  58.64   6.87]]

 Coordinates Concentration ::
[[221.45593863  66.08811021   6.98      ]
 [222.58460511  69.18909586   6.98      ]
 [228.17923182  64.38595605   6.98      ]
 [224.94447869  63.86062547   7.28      ]
 [225.7490888   68.99507798   7.3       ]
 [228.36720395  67.32916289   8.48      ]
 [225.81663006  66.25684165   6.87      ]]


  /content/gdrive/MyDrive/ACSE-9/ClarenceCentre/run_Clip_ToSend/ClarenceCentre_0.vtu
     Read file
     Gathering  coordinates
           Set points into data...
           Map data into probe... VTK version :: 9 . 0
     Initialise cell Locator
           Check point Validity
           ...  0.0 invalid points
     Extract Data
no

KeyboardInterrupt: ignored

In [ ]:
print(type(CO2_all))
print(type(CO2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Import pod coeffs and do below process in concetenating pod_coeffs with CO2 as well as time_levels with pod_coeffs and CO2 

In [4]:
pca_compress = joblib.load('/content/gdrive/MyDrive/ACSE-9/output_pod_files/pod_coefficients_410.pkl') 
CO2_sensor = joblib.load('/content/gdrive/MyDrive/ACSE-9/models/sensor_CO2_410.pkl')

In [5]:
print(CO2_sensor[2,:])

[ 608.69587777  491.06084034 1436.         1436.         1436.
 1436.         1436.        ]


In [6]:
print(pca_compress.shape)
print(CO2_sensor.shape)

(410, 43)
(410, 7)


scaling CO2 from sensor locations

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_enhanced = MinMaxScaler((-1,1))
scaler_enhanced.fit(CO2_sensor)
norm_sensor_CO2 = scaler_enhanced.transform(CO2_sensor)
# CO2_scaled = scaler_minmax_enhanced.fit_transform(CO2)
print("Standardised CO2 at sensor locations: ", norm_sensor_CO2)

Standardised CO2 at sensor locations:  [[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 0.9737602   0.95008819  1.         ...  1.          1.
   1.        ]
 [-0.59716197 -0.82432065  1.         ...  1.          1.
   1.        ]
 ...
 [-0.99544474 -0.98879937 -0.99900326 ... -0.99823697 -0.96347561
  -0.9771921 ]
 [-0.99476439 -0.98835156 -0.9990045  ... -0.99919844 -0.98451205
  -0.97629523]
 [-0.9941548  -0.98801283 -0.99899582 ... -1.         -1.
  -0.97529972]]


In [9]:
X_train_pca = pca_compress
print(X_train_pca.shape)
print(norm_sensor_CO2.shape, "\n\n")

enhanced_data = np.concatenate((X_train_pca, norm_sensor_CO2), axis=1)
print(enhanced_data.shape)

joblib.dump(enhanced_data, '/content/gdrive/MyDrive/ACSE-9/models/enhanced_data_410.pkl')
joblib.dump(scaler_enhanced, '/content/gdrive/MyDrive/ACSE-9/models/CO2_scaler_minmax_410.pkl')

(410, 43)
(410, 7) 


(410, 50)


['/content/gdrive/MyDrive/ACSE-9/models/CO2_scaler_minmax_410.pkl']

In [30]:
#TESTING
## DELETE
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler((-1, 1))
X_train_scaled = scaler_minmax.fit_transform(X_train_pca)
np.allclose(X_train_pca, scaler_minmax.inverse_transform(X_train_scaled))

enhanced_data = np.concatenate((X_train_scaled, norm_sensor_CO2), axis=1)
print(enhanced_data.shape)

print(enhanced_data[:,:43].max())
print(np.allclose(enhanced_data[:,:43].max(), X_train_pca.max()))
print(enhanced_data[:,43:].max())
print(enhanced_data.max())

(410, 50)
1.0000000000000002
False
1.0000000000000002
1.0000000000000002


In [26]:
print(enhanced_data[:,:43].max())
print(np.allclose(enhanced_data[:,:43].max(), X_train_pca.max()))
print(enhanced_data[:,43:].max())

475.15055604402625
True
1.0000000000000002


BELOW IS DELETABLE NOTES

In [ ]:
##
times = [np.array(TimeVTU)]
print("Times:\n", times)
print(np.shape(times), "\n")

print("CO2:\n", CO2)
print(np.shape(CO2), "\n")

alpha = np.append(times, np.transpose(CO2))
print("appending: \n")
print(np.shape(alpha))
print(alpha, "\n")

applying_axis0 = np.append(times, np.transpose(CO2), axis=0)
print("appending in axis=0:\n")
print(applying_axis0.shape)
print(applying_axis0, "\n")

alpha_Transpose = np.append(times, np.transpose(CO2), axis=0).T
print("transposing:\n")
print(alpha_Transpose.shape)
print(alpha_Transpose)
print(np.allclose(alpha_Transpose, CO2_all),"\n\n")

nPOD = 10
nVTU = 3
pod_data = np.arange(10, 40, 1).reshape(nVTU, nPOD)
print("POD array:\n", pod_data)
print(pod_data.shape)

# # just appending time with pod_data
# time_pod = np.append(times, pod_data.T, axis=0).T
# pprint.pprint(time_pod)
# print(np.shape(time_pod))
# just_times = []
# for i in range(0, nVTU):
#   just_times.append(time_pod[i][0])
# print(just_times)
# print(np.shape(just_times))


Times:
 [array([  0.        ,   1.9898429 ,   4.00484264,   5.97867793,
         8.00982706,  10.02021573,  12.02481123,  13.98274579,
        16.06566173,  18.01166381,  20.06989921,  22.03393403,
        23.78317308,  25.84587113,  28.08545312,  30.02032156,
        31.77094132,  34.14753283,  35.79313322,  38.06560261,
        39.93259469,  41.98828451,  44.04655777,  46.03227038,
        47.97901246,  49.99739466,  51.94692764,  54.0589973 ,
        55.9097836 ,  58.06239377,  59.93479071,  62.06967318,
        64.11904859,  65.87107963,  68.06987217,  69.94624102,
        72.02312602,  73.91167233,  75.94302904,  78.02260652,
        79.98425182,  81.84433766,  83.78471041,  85.8274619 ,
        88.00226999,  90.09753974,  91.80515975,  93.8225811 ,
        95.87453803,  98.08032782,  99.80548599, 101.76315703,
       104.36512329, 105.59872402, 108.44227164, 110.11809663,
       111.85680672, 113.97987529, 116.07215298, 117.81774249,
       119.83987719, 121.90970916, 123.8536428

In [ ]:
## BELOW WORKS!

# appending all together -> (times, nPOD+co2)
nPOD = 10
nVTU = 3
pod_data = np.arange(10, 40, 1).reshape(nVTU, nPOD)
print("POD array:\n", pod_data)
print(pod_data.shape)

#joining pod_coeffs with co2 at sensors:
CO2_try = CO2[0:3][0:10]
print(CO2_try)
print(np.shape(CO2_try))

all_data = np.concatenate((pod_data, CO2_try), axis=1)
print("\n", all_data)

print("\n\n\n")
# all_data_with_time = np.append(times, all_data.T, axis=0).T
# print(all_data_with_time)
# print(all_data_with_time.shape)

POD array:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
(3, 10)
[[1436.         1436.         1436.         1436.         1436.
  1436.         1436.        ]
 [1422.40820872 1410.14729655 1436.         1436.         1436.
  1436.         1436.        ]
 [ 608.69587777  491.06084034 1436.         1436.         1436.
  1436.         1436.        ]]
(3, 7)

 [[  10.           11.           12.           13.           14.
    15.           16.           17.           18.           19.
  1436.         1436.         1436.         1436.         1436.
  1436.         1436.        ]
 [  20.           21.           22.           23.           24.
    25.           26.           27.           28.           29.
  1422.40820872 1410.14729655 1436.         1436.         1436.
  1436.         1436.        ]
 [  30.           31.           32.           33.           34.
    35.           36.           37.           38.           39.
   608.6958